### ISSUE TITLE
Can´t compile because of unknown setMatrixWidth

### ISSUE THREAD

**Issue by MKleinSB** [tballmsft/microbitSparkletGames#1]
I wanted to compile the programs in Makecode beta, but there is an error
![grafik](https://user-images.githubusercontent.com/37311672/120819620-0bc02a80-c554-11eb-96c7-a5800b7566da.png)

**Comment by tballmsft** [comment]
works fine for me. Are you sure you are in beta?

**Comment by MKleinSB** [comment]
Ah, yes, it was my mistake. By the way, I copied some 16x16 picture like the Strawberry from Makecode arcade. Drawimage didn´t show the Colors of the characters a-f. To show all the colors I simply have to change drawImage to 

```

function drawImage(img: string) {
    let c = 0, r = 0;
    for (let i = 0; i < img.length; i++) {
        let dot = img[i] == "."
        let hex = "01234567890abcdef".includes(img[i])
        if (dot || hex) {
            if (hex) {
                let colIndex = img.charCodeAt(i) - "0".charCodeAt(0);
                if (colIndex > 10) {
                    colIndex = colIndex - 39
                }
                screen.setPixel(c, r, toRGB(colIndex));
            }
            c++; if (c == 16) { c = 0; r++ }
        }
    }
    screen.show();
}
```

Thanks for the fun playing with it!
